// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package application

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComDewepproGoAppApplication(in *jlexer.Lexer, out *BaseConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "env":
			out.Env = string(in.String())
		case "pid":
			out.PidFile = string(in.String())
		case "level":
			out.Level = uint32(in.Uint32())
		case "log":
			out.LogFile = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComDewepproGoAppApplication(out *jwriter.Writer, in BaseConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"env\":"
		out.RawString(prefix[1:])
		out.String(string(in.Env))
	}
	{
		const prefix string = ",\"pid\":"
		out.RawString(prefix)
		out.String(string(in.PidFile))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Level))
	}
	{
		const prefix string = ",\"log\":"
		out.RawString(prefix)
		out.String(string(in.LogFile))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BaseConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComDewepproGoAppApplication(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BaseConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComDewepproGoAppApplication(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BaseConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComDewepproGoAppApplication(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BaseConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComDewepproGoAppApplication(l, v)
}
