language: go
sudo: false

go:
  - "1.13.x"
  - "1.14.x"
  - tip

env:
  - GO111MODULE=on

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)