// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package app

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComDewepproGoApp(in *jlexer.Lexer, out *ConfigLogger) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "env":
			out.Env = string(in.String())
		case "log":
			out.LogFile = string(in.String())
		case "pid":
			out.PidFile = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComDewepproGoApp(out *jwriter.Writer, in ConfigLogger) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"env\":"
		out.RawString(prefix[1:])
		out.String(string(in.Env))
	}
	{
		const prefix string = ",\"log\":"
		out.RawString(prefix)
		out.String(string(in.LogFile))
	}
	{
		const prefix string = ",\"pid\":"
		out.RawString(prefix)
		out.String(string(in.PidFile))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ConfigLogger) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComDewepproGoApp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ConfigLogger) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComDewepproGoApp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ConfigLogger) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComDewepproGoApp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ConfigLogger) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComDewepproGoApp(l, v)
}
